### ISSUE TITLE
[Conversion] 파일 변환 관련 문제

### ISSUE THREAD

**Issue by C4NU** [C4NU/Paddie#53]
### 재현 스텝

1. 사진 변환 작업
2. 변환이 끝나고 파일 목록이 비워지고 새로운 사진들을 추가함.
3. 변환을 수행하면 1번 작업에서 변환했던 사진이 변환되어 생성되고 2번의 새로운 사진은 변환이 이루어지지 않음

**Comment by komastar** [comment]
해보니까 잘 되는데 재현 방법 있으면 알려주고 아니면 이슈 닫으면 될듯

**Comment by komastar** [comment]
BFS done
